package enums;

public enum ItemAction {
    ITEM_CREATE,
    ITEM_UPDATE,
    ITEM_DELETE,
    ITEM_ARCHIVE,
    ITEM_UNARCHIVE,
    ITEM_RESTORE,
    ITEM_LIST,
    ITEM_UNLIST,
    ITEM_APPROVE,
    ITEM_REJECT,
    ITEM_UPLOAD_IMAGE,
    ITEM_DELETE_IMAGE,
    ITEM_MARK_AVAILABLE,
    ITEM_MARK_UNAVAILABLE
}