package enums;

public enum TransactionAction {
    TRANSACTION_BUY,
    TRANSACTION_SELL,
    TRANSACTION_CANCEL,
    TRANSACTION_COMPLETE,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    TRADE_INITIATE,
    TRADE_ACCEPT,
    TRADE_DECLINE,
    TRADE_CANCEL,
    TRADE_COMPLETE,
    BORROW_REQUEST,
    BORROW_APPROVE,
    BORROW_DECLINE,
    BORROW_RETURN,
    BORROW_CANCEL,
    BORROW_COMPLETE
}