package enums;

public enum UserAction {
    USER_REGISTER,
    USER_LOGIN,
    USER_LOGOUT,
    USER_UPDATE_PROFILE,
    USER_CHANGE_PASSWORD,
    USER_UPLOAD_PROFILE,
    USER_ARCHIVE,
    USER_UNARCHIVE,
    USER_RESTORE,
    USER_DELETE,
    USER_ROLE_UPDATE
}